// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqZVioYCsMAJPF2dkBH1dppqgsNGLKh0g',
    appId: '1:505727151968:web:8163a2923b5fe63a593805',
    messagingSenderId: '505727151968',
    projectId: 'checklist-memo-app',
    authDomain: 'checklist-memo-app.firebaseapp.com',
    storageBucket: 'checklist-memo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6t5pyTpKiknv5lhz91Q2-EIfOGiEZK48',
    appId: '1:505727151968:android:beec0b9b6144d10e593805',
    messagingSenderId: '505727151968',
    projectId: 'checklist-memo-app',
    storageBucket: 'checklist-memo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuHMDfe7mjIHCacGp7sx9PocOCIgXxrjA',
    appId: '1:505727151968:ios:611ba1ac078f4883593805',
    messagingSenderId: '505727151968',
    projectId: 'checklist-memo-app',
    storageBucket: 'checklist-memo-app.firebasestorage.app',
    iosBundleId: 'com.example.memoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuHMDfe7mjIHCacGp7sx9PocOCIgXxrjA',
    appId: '1:505727151968:ios:611ba1ac078f4883593805',
    messagingSenderId: '505727151968',
    projectId: 'checklist-memo-app',
    storageBucket: 'checklist-memo-app.firebasestorage.app',
    iosBundleId: 'com.example.memoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqZVioYCsMAJPF2dkBH1dppqgsNGLKh0g',
    appId: '1:505727151968:web:fb185324e1be380f593805',
    messagingSenderId: '505727151968',
    projectId: 'checklist-memo-app',
    authDomain: 'checklist-memo-app.firebaseapp.com',
    storageBucket: 'checklist-memo-app.firebasestorage.app',
  );
}
